[
  {
    "command": "pip install -e ./python/dolfinx",
    "success": false,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nObtaining file:///app/repo_to_process/python/dolfinx\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Checking if build backend supports build_editable: started\n  Checking if build backend supports build_editable: finished with status 'done'\n  Getting requirements to build editable: started\n  Getting requirements to build editable: finished with status 'error'\n",
    "stderr": "  error: subprocess-exited-with-error\n  \n  × Getting requirements to build editable did not run successfully.\n  │ exit code: 1\n  ╰─> [14 lines of output]\n      error: Multiple top-level packages discovered in a flat-layout: ['la', 'io', 'nls', 'fem', 'wrappers'].\n      \n      To avoid accidental inclusion of unwanted files or directories,\n      setuptools will not proceed with this build.\n      \n      If you are trying to create a single distribution with multiple packages\n      on purpose, you should not rely on automatic discovery.\n      Instead, consider the following options:\n      \n      1. set up custom discovery (`find` directive with `include` or `exclude`)\n      2. use a `src-layout`\n      3. explicitly set `py_modules` or `packages` with a list of names\n      \n      To find more information, look for \"package discovery\" on setuptools docs.\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\nerror: subprocess-exited-with-error\n\n× Getting requirements to build editable did not run successfully.\n│ exit code: 1\n╰─> See above for output.\n\nnote: This error originates from a subprocess, and is likely not a problem with pip.\n",
    "execution_time": 2.2046806812286377
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0\nrootdir: /app/repo_to_process\ncollected 0 items / 1 error\n\n==================================== ERRORS ====================================\n_________________________ ERROR collecting python/test _________________________\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1050: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:1027: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:688: in _load_unlocked\n    ???\n/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py:186: in exec_module\n    exec(co, module.__dict__)\npython/test/conftest.py:13: in <module>\n    from dolfinx.la import vector as dolfinx_vector\nE   ModuleNotFoundError: No module named 'dolfinx'\n=========================== short test summary info ============================\nERROR python/test - ModuleNotFoundError: No module named 'dolfinx'\n!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!\n=============================== 1 error in 0.51s ===============================\n",
    "stderr": "",
    "execution_time": 0.747300386428833
  }
]