[
  {
    "command": "pip install \"numpy==1.24.4\"",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nCollecting numpy==1.24.4\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/10/be/ae5bf4737cb79ba437879915791f6f26d92583c738d7d960ad94e5c36adf/numpy-1.24.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)\nInstalling collected packages: numpy\nSuccessfully installed numpy-1.24.4\n",
    "stderr": "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\ngeoparse 2.0.3 requires pandas>=0.17, which is not installed.\ncufflinks 0.17.3 requires pandas>=0.19.2, which is not installed.\ndash-bio 1.0.2 requires pandas, which is not installed.\ndash-bio 1.0.2 requires scipy, which is not installed.\ndatashader 0.14.4 requires numba>=0.51, which is not installed.\ndatashader 0.14.4 requires pandas, which is not installed.\ndatashader 0.14.4 requires scipy, which is not installed.\ndatashader 0.14.4 requires xarray, which is not installed.\nscikit-image 0.20.0 requires scipy>=1.8; python_version > \"3.9\", which is not installed.\nscikit-learn 1.7.1 requires scipy>=1.8.0, which is not installed.\nstatsmodels 0.14.2 requires pandas!=2.1.0,>=1.4, which is not installed.\nstatsmodels 0.14.2 requires scipy!=1.9.2,>=1.8, which is not installed.\numap-learn 0.5.1 requires numba>=0.49, which is not installed.\numap-learn 0.5.1 requires scipy>=1.0, which is not installed.\nWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 3.054072856903076
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0\nrootdir: /app/repo_to_process\nconfigfile: pyproject.toml\nplugins: dash-3.2.0, anyio-4.10.0\ncollected 1522 items / 16 errors\n\n==================================== ERRORS ====================================\n_____ ERROR collecting plotly/matplotlylib/mplexporter/tests/test_utils.py _____\nImportError while importing test module '/app/repo_to_process/plotly/matplotlylib/mplexporter/tests/test_utils.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nplotly/matplotlylib/mplexporter/tests/test_utils.py:2: in <module>\n    from . import plt\nE   ImportError: cannot import name 'plt' from 'plotly.matplotlylib.mplexporter.tests' (/app/repo_to_process/plotly/matplotlylib/mplexporter/tests/__init__.py)\n__________ ERROR collecting tests/test_io/test_to_from_plotly_json.py __________\nImportError while importing test module '/app/repo_to_process/tests/test_io/test_to_from_plotly_json.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_io/test_to_from_plotly_json.py:6: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_optional/test_figure_factory/test_figure_factory.py _\nImportError while importing test module '/app/repo_to_process/tests/test_optional/test_figure_factory/test_figure_factory.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_optional/test_figure_factory/test_figure_factory.py:7: in <module>\n    from ...test_optional.test_utils.test_utils import np_inf\ntests/test_optional/test_utils/test_utils.py:15: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n__ ERROR collecting tests/test_optional/test_matplotlylib/test_date_times.py ___\nImportError while importing test module '/app/repo_to_process/tests/test_optional/test_matplotlylib/test_date_times.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_optional/test_matplotlylib/test_date_times.py:6: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_________________ ERROR collecting tests/test_optional/test_px _________________\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n<frozen importlib._bootstrap>:1050: in _gcd_import\n    ???\n<frozen importlib._bootstrap>:1027: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:688: in _load_unlocked\n    ???\n/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py:186: in exec_module\n    exec(co, module.__dict__)\ntests/test_optional/test_px/conftest.py:1: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n________ ERROR collecting tests/test_optional/test_utils/test_utils.py _________\nImportError while importing test module '/app/repo_to_process/tests/test_optional/test_utils/test_utils.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_optional/test_utils/test_utils.py:15: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n__ ERROR collecting tests/test_plotly_utils/validators/test_any_validator.py ___\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_any_validator.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_any_validator.py:4: in <module>\n    from ...test_optional.test_utils.test_utils import np_nan, np_inf\ntests/test_optional/test_utils/test_utils.py:15: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_plotly_utils/validators/test_boolean_validator.py _\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_boolean_validator.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_boolean_validator.py:3: in <module>\n    from ...test_optional.test_utils.test_utils import np_nan\ntests/test_optional/test_utils/test_utils.py:15: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_plotly_utils/validators/test_dataarray_validator.py _\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_dataarray_validator.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_dataarray_validator.py:4: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_plotly_utils/validators/test_enumerated_validator.py _\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_enumerated_validator.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_enumerated_validator.py:3: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_plotly_utils/validators/test_integer_validator.py _\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_integer_validator.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_integer_validator.py:6: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_plotly_utils/validators/test_number_validator.py _\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_number_validator.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_number_validator.py:6: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_plotly_utils/validators/test_pandas_series_input.py _\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_pandas_series_input.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_pandas_series_input.py:3: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_plotly_utils/validators/test_string_validator.py _\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_string_validator.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_string_validator.py:5: in <module>\n    from ...test_optional.test_utils.test_utils import np_nan\ntests/test_optional/test_utils/test_utils.py:15: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n_ ERROR collecting tests/test_plotly_utils/validators/test_subplotid_validator.py _\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_subplotid_validator.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_subplotid_validator.py:3: in <module>\n    from ...test_optional.test_utils.test_utils import np_nan, np_inf\ntests/test_optional/test_utils/test_utils.py:15: in <module>\n    import pandas as pd\nE   ModuleNotFoundError: No module named 'pandas'\n___ ERROR collecting tests/test_plotly_utils/validators/test_xarray_input.py ___\nImportError while importing test module '/app/repo_to_process/tests/test_plotly_utils/validators/test_xarray_input.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests/test_plotly_utils/validators/test_xarray_input.py:3: in <module>\n    import xarray\nE   ModuleNotFoundError: No module named 'xarray'\n=============================== warnings summary ===============================\nplotly/conftest.py:4\n  /app/repo_to_process/plotly/conftest.py:4: PytestRemovedIn9Warning:\n  \n  The (path: py.path.local) argument is deprecated, please use (collection_path: pathlib.Path)\n  see https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path\n\n-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n=========================== short test summary info ============================\nERROR plotly/matplotlylib/mplexporter/tests/test_utils.py\nERROR tests/test_io/test_to_from_plotly_json.py\nERROR tests/test_optional/test_figure_factory/test_figure_factory.py\nERROR tests/test_optional/test_matplotlylib/test_date_times.py\nERROR tests/test_optional/test_px - ModuleNotFoundError: No module named 'pan...\nERROR tests/test_optional/test_utils/test_utils.py\nERROR tests/test_plotly_utils/validators/test_any_validator.py\nERROR tests/test_plotly_utils/validators/test_boolean_validator.py\nERROR tests/test_plotly_utils/validators/test_dataarray_validator.py\nERROR tests/test_plotly_utils/validators/test_enumerated_validator.py\nERROR tests/test_plotly_utils/validators/test_integer_validator.py\nERROR tests/test_plotly_utils/validators/test_number_validator.py\nERROR tests/test_plotly_utils/validators/test_pandas_series_input.py\nERROR tests/test_plotly_utils/validators/test_string_validator.py\nERROR tests/test_plotly_utils/validators/test_subplotid_validator.py\nERROR tests/test_plotly_utils/validators/test_xarray_input.py\n!!!!!!!!!!!!!!!!!!! Interrupted: 16 errors during collection !!!!!!!!!!!!!!!!!!!\n======================== 1 warning, 16 errors in 1.91s =========================\n",
    "stderr": "",
    "execution_time": 3.1558971405029297
  }
]