[
  {
    "command": "pip install pytest-cov",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nCollecting pytest-cov\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/bc/16/4ea354101abb1287856baa4af2732be351c7bee728065aed451b678153fd/pytest_cov-6.2.1-py3-none-any.whl (24 kB)\nRequirement already satisfied: pytest>=6.2.5 in /usr/local/lib/python3.10/dist-packages (from pytest-cov) (8.4.1)\nCollecting coverage>=7.5 (from coverage[toml]>=7.5->pytest-cov)\n  Downloading https://repo.huaweicloud.com/repository/pypi/packages/b9/8e/5a8835fb0122a2e2a108bf3527931693c4625fdc4d953950a480b9625852/coverage-7.10.2-cp310-cp310-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (243 kB)\nRequirement already satisfied: pluggy>=1.2 in /usr/local/lib/python3.10/dist-packages (from pytest-cov) (1.6.0)\nRequirement already satisfied: tomli in /usr/local/lib/python3.10/dist-packages (from coverage[toml]>=7.5->pytest-cov) (2.2.1)\nRequirement already satisfied: exceptiongroup>=1 in /usr/local/lib/python3.10/dist-packages (from pytest>=6.2.5->pytest-cov) (1.3.0)\nRequirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.10/dist-packages (from pytest>=6.2.5->pytest-cov) (2.1.0)\nRequirement already satisfied: packaging>=20 in /usr/local/lib/python3.10/dist-packages (from pytest>=6.2.5->pytest-cov) (25.0)\nRequirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.10/dist-packages (from pytest>=6.2.5->pytest-cov) (2.19.2)\nRequirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from exceptiongroup>=1->pytest>=6.2.5->pytest-cov) (4.14.1)\nInstalling collected packages: coverage, pytest-cov\n\nSuccessfully installed coverage-7.10.2 pytest-cov-6.2.1\n",
    "stderr": "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 2.0229456424713135
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "\u001b[1m============================= test session starts ==============================\u001b[0m\nplatform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0 -- /usr/bin/python3\ncachedir: .pytest_cache\nrootdir: /app/repo_to_process\nconfigfile: pyproject.toml\nplugins: cov-6.2.1\n\u001b[1mcollecting ... \u001b[0mcollected 0 items / 1 error\n\n==================================== ERRORS ====================================\n\u001b[31m\u001b[1m____________________________ ERROR collecting dask _____________________________\u001b[0m\n\u001b[1m\u001b[31m/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py\u001b[0m:712: in _importconftest\n    \u001b[0mmod = import_path(\u001b[90m\u001b[39;49;00m\n\u001b[1m\u001b[31m/usr/local/lib/python3.10/dist-packages/_pytest/pathlib.py\u001b[0m:610: in import_path\n    \u001b[0m\u001b[94mraise\u001b[39;49;00m ImportPathMismatchError(module_name, module_file, path)\u001b[90m\u001b[39;49;00m\n\u001b[1m\u001b[31mE   _pytest.pathlib.ImportPathMismatchError: ('dask.conftest', '/usr/local/lib/python3.10/dist-packages/dask/conftest.py', PosixPath('/app/repo_to_process/dask/conftest.py'))\u001b[0m\n\u001b[33m=============================== warnings summary ===============================\u001b[0m\n../../usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py:1474\n  /usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py:1474: PytestConfigWarning: Unknown config option: timeout\n  \n    self._warn_or_fail_if_strict(f\"Unknown config option: {key}\\n\")\n\n../../usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py:1474\n  /usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py:1474: PytestConfigWarning: Unknown config option: timeout_method\n  \n    self._warn_or_fail_if_strict(f\"Unknown config option: {key}\\n\")\n\n-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n\u001b[36m\u001b[1m=========================== short test summary info ============================\u001b[0m\n\u001b[31mERROR\u001b[0m dask - _pytest.pathlib.ImportPathMismatchError: ('dask.conftest', '/usr/local/lib/...\n!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!\n\u001b[31m========================= \u001b[33m2 warnings\u001b[0m, \u001b[31m\u001b[1m1 error\u001b[0m\u001b[31m in 0.56s\u001b[0m\u001b[31m =========================\u001b[0m\n",
    "stderr": "",
    "execution_time": 1.4970142841339111
  }
]