[
  {
    "command": "pip install cython meson meson-python",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nCollecting cython\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/b4/eb/8c47ba21177929f9122e7aceca9fe1f9f5a037e705226f8a5a9113fb53ba/cython-3.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)\nCollecting meson\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/4b/bf/1a2f345a6e8908cd0b17c2f0a3c4f41667f724def84276ff1ce87d003594/meson-1.8.3-py3-none-any.whl (1.0 MB)\nCollecting meson-python\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/28/58/66db620a8a7ccb32633de9f403fe49f1b63c68ca94e5c340ec5cceeb9821/meson_python-0.18.0-py3-none-any.whl (28 kB)\nRequirement already satisfied: packaging>=23.2 in /usr/local/lib/python3.10/dist-packages (from meson-python) (25.0)\nCollecting pyproject-metadata>=0.9.0 (from meson-python)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/7e/b1/8e63033b259e0a4e40dd1ec4a9fee17718016845048b43a36ec67d62e6fe/pyproject_metadata-0.9.1-py3-none-any.whl (18 kB)\nRequirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from meson-python) (2.2.1)\nInstalling collected packages: pyproject-metadata, meson, cython, meson-python\n\nSuccessfully installed cython-3.1.2 meson-1.8.3 meson-python-0.18.0 pyproject-metadata-0.9.1\n",
    "stderr": "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 2.8984217643737793
  },
  {
    "command": "pip install .",
    "success": false,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nProcessing /app/repo_to_process\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Installing backend dependencies: started\n  Installing backend dependencies: finished with status 'done'\n  Preparing metadata (pyproject.toml): started\n  Preparing metadata (pyproject.toml): finished with status 'error'\n",
    "stderr": "  error: subprocess-exited-with-error\n  \n  × Preparing metadata (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─> [22 lines of output]\n      + meson setup /app/repo_to_process /app/repo_to_process/.mesonpy-cmtkfzqa -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/app/repo_to_process/.mesonpy-cmtkfzqa/meson-python-native-file.ini\n      The Meson build system\n      Version: 1.8.3\n      Source dir: /app/repo_to_process\n      Build dir: /app/repo_to_process/.mesonpy-cmtkfzqa\n      Build type: native build\n      Project name: PyWavelets\n      Project version: 1.10.0.dev0\n      C compiler for the host machine: cc (gcc 11.4.0 \"cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0\")\n      C linker for the host machine: cc ld.bfd 2.38\n      Cython compiler for the host machine: cython (cython 3.1.2)\n      Host machine cpu family: x86_64\n      Host machine cpu: x86_64\n      Program cython found: YES (/tmp/pip-build-env-qhessu3g/overlay/local/bin/cython)\n      Program python found: YES (/usr/bin/python3)\n      Did not find pkg-config by name 'pkg-config'\n      Found pkg-config: NO\n      Run-time dependency python found: NO (tried pkgconfig, pkgconfig and sysconfig)\n      \n      ../meson.build:17:12: ERROR: Python dependency not found\n      \n      A full log can be found at /app/repo_to_process/.mesonpy-cmtkfzqa/meson-logs/meson-log.txt\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\nerror: metadata-generation-failed\n\n× Encountered error while generating package metadata.\n╰─> See above for output.\n\nnote: This is an issue with the package mentioned above, not pip.\nhint: See above for details.\n",
    "execution_time": 6.414889335632324
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.4.1, pluggy-1.6.0\nrootdir: /app/repo_to_process\nconfigfile: pytest.ini\nplugins: cov-6.2.1\ncollected 0 items / 1 error\n\n==================================== ERRORS ====================================\n____________________________ ERROR collecting pywt _____________________________\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n        level      = 0\n        name       = 'pywt.conftest'\n        package    = None\n<frozen importlib._bootstrap>:1050: in _gcd_import\n    ???\n        level      = 0\n        name       = 'pywt.conftest'\n        package    = None\n<frozen importlib._bootstrap>:1027: in _find_and_load\n    ???\n        import_    = <function _gcd_import at 0x7f8d16d4b400>\n        module     = <object object at 0x7f8d16d70060>\n        name       = 'pywt.conftest'\n<frozen importlib._bootstrap>:992: in _find_and_load_unlocked\n    ???\n        import_    = <function _gcd_import at 0x7f8d16d4b400>\n        name       = 'pywt.conftest'\n        parent     = 'pywt'\n        path       = None\n<frozen importlib._bootstrap>:241: in _call_with_frames_removed\n    ???\n        args       = ('pywt',)\n        f          = <function _gcd_import at 0x7f8d16d4b400>\n        kwds       = {}\n<frozen importlib._bootstrap>:1050: in _gcd_import\n    ???\n        level      = 0\n        name       = 'pywt'\n        package    = None\n<frozen importlib._bootstrap>:1027: in _find_and_load\n    ???\n        import_    = <function _gcd_import at 0x7f8d16d4b400>\n        module     = <object object at 0x7f8d16d70060>\n        name       = 'pywt'\n<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked\n    ???\n        import_    = <function _gcd_import at 0x7f8d16d4b400>\n        name       = 'pywt'\n        parent     = ''\n        path       = None\n        spec       = ModuleSpec(name='pywt', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f8d15635810>, origin='/app/repo_to_process/pywt/__init__.py', submodule_search_locations=['/app/repo_to_process/pywt'])\n<frozen importlib._bootstrap>:688: in _load_unlocked\n    ???\n        module     = <module 'pywt' from '/app/repo_to_process/pywt/__init__.py'>\n        spec       = ModuleSpec(name='pywt', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f8d15635810>, origin='/app/repo_to_process/pywt/__init__.py', submodule_search_locations=['/app/repo_to_process/pywt'])\n<frozen importlib._bootstrap_external>:883: in exec_module\n    ???\n        code       = <code object <module> at 0x7f8d154403a0, file \"/app/repo_to_process/pywt/__init__.py\", line 1>\n        module     = <module 'pywt' from '/app/repo_to_process/pywt/__init__.py'>\n        self       = <_frozen_importlib_external.SourceFileLoader object at 0x7f8d15635810>\n<frozen importlib._bootstrap>:241: in _call_with_frames_removed\n    ???\n        args       = (<code object <module> at 0x7f8d154403a0, file \"/app/repo_to_process/pywt/__init__.py\", line 1>, {'__builtins__': {'Ar... packets signal decomposition and reconstruction module.\\n', '__file__': '/app/repo_to_process/pywt/__init__.py', ...})\n        f          = <built-in function exec>\n        kwds       = {}\npywt/__init__.py:13: in <module>\n    from ._extensions._pywt import *\nE   ModuleNotFoundError: No module named 'pywt._extensions._pywt'\n        __builtins__ = <builtins>\n        __cached__ = '/app/repo_to_process/pywt/__pycache__/__init__.cpython-310.pyc'\n        __doc__    = '\\nDiscrete forward and inverse wavelet transform, stationary wavelet transform,\\nwavelet packets signal decomposition and reconstruction module.\\n'\n        __file__   = '/app/repo_to_process/pywt/__init__.py'\n        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7f8d15635810>\n        __name__   = 'pywt'\n        __package__ = 'pywt'\n        __path__   = ['/app/repo_to_process/pywt']\n        __spec__   = ModuleSpec(name='pywt', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f8d15635810>, origin='/app/repo_to_process/pywt/__init__.py', submodule_search_locations=['/app/repo_to_process/pywt'])\n        _extensions = <module 'pywt._extensions' from '/app/repo_to_process/pywt/_extensions/__init__.py'>\n=========================== short test summary info ============================\nERROR pywt - ModuleNotFoundError: No module named 'pywt._extensions._pywt'\n!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!\n=============================== 1 error in 0.11s ===============================\n",
    "stderr": "",
    "execution_time": 0.32251858711242676
  }
]